export default {
    navigation: {
        timetable: 'Timetable',
        map: 'Map',
        campusMap: 'Campus Map',
        food: 'Food',
        settings: 'Settings',
        preferences: 'Preferences',
        flags: 'Flags',
        flagsSearch: 'Search flags',
        allergensSearch: 'Search allergens',
        allergens: 'Allergens',
        details: 'Details',
        theme: 'Appearance',
        profile: 'Profile',
        about: 'About',
        advancedSearch: 'Advanced Search',
        calendar: 'Calendar',
        examDetails: 'Exam Details',
        lecturers: {
            title: 'Lecturers',
            search: 'Search all lecturers',
        },
        lecturer: 'Lecturer Details',
        mobility: 'Mobility',
        grades: 'Grades',
        news: 'THI News',
    },
    cards: {
        titles: {
            timetable: 'Timetable',
            mobility: 'Mobility',
            calendar: 'Calendar',
            rooms: 'Rooms',
            lecturers: 'Lecturers',
            news: 'THI News',
            library: 'Library',
            events: 'Events',
            reimanns: 'Reimanns',
            canisius: 'Canisius Konvikt',
            mensa: 'Mensa',
            food: 'Food',
        },
        events: {
            by: 'by {{name}}',
        },
        calendar: {
            exam: 'exam {{name}}',
            ends: 'ends ',
        },
    },
    shortcuts: {
        timetableDescription: 'Lectures, events etc.',
    },
}
