apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neuland-next-staging
  namespace: neuland-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neuland-next-staging
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70