export default {
    navigation: {
        timetable: 'Stundenplan',
        map: 'Karte',
        food: 'Essen',
        campusMap: 'Campus Karte',
        settings: 'Einstellungen',
        preferences: 'Präferenzen',
        flags: 'Kennzeichnungen',
        flagsSearch: 'Suche Kennzeichnungen',
        allergensSearch: 'Suche Allergene',
        allergens: 'Allergene',
        details: 'Details',
        theme: 'Design',
        profile: 'Profil',
        about: 'Über',
        advancedSearch: 'Erweiterte Suche',
        calendar: 'Kalender',
        examDetails: 'Prüfungsdetails',
        lecturers: {
            title: 'Dozenten',
            search: 'Suche alle Dozenten',
        },
        lecturer: 'Dozenten-Details',
        grades: 'Noten',
        news: 'THI Neuigkeiten',
        library: 'Bibliothek',
        libraryCode: 'Bibliotheksnummer',
        notifications: 'Benachrichtigungen',
        licenses: 'Lizenzen',
        license: 'Lizenz',
    },
    cards: {
        titles: {
            timetable: 'Stundenplan',
            calendar: 'Kalender',
            rooms: 'Räume',
            lecturers: 'Dozenten',
            news: 'THI Neuigkeiten',
            library: 'Bibliothek',
            events: 'Veranstaltungen',
            reimanns: 'Reimanns',
            canisius: 'Canisius Konvikt',
            mensa: 'Mensa',
            food: 'Essen',
            login: 'Anmelden',
        },
        events: {
            by: 'von {{name}}',
        },
        calendar: {
            exam: 'Prüfung {{name}}',
            ends: 'endet ',
        },
        timetable: {
            startingSoon: 'startet in {{count}} min',
            startingSoon_plural: 'startet in {{count}} mins',
            ongoing: 'endet um {{time}}',
            endingSoon: 'endet in {{count}} min',
            endingSoon_plural: 'endet in {{count}} mins',
        },
        login: {
            title: 'Stundenplan, Noten, Räume und mehr',
            message: 'Melde dich an, um alle Funktionen freizuschalten.',
        },
    },
    contextMenu: {
        reset: 'Karten zurücksetzen',
        hide: 'Karte ausblenden',
        settings: 'Dashboard Einstellungen',
    },
    unmatched: {
        title: 'Nicht gefunden',
        error: {
            title: 'nicht gefunden',
            message: 'Die angeforderte Seite ist nicht verfügbar.',
            button: 'Zurück',
        },
    },
}
