export default {
    navigation: {
        timetable: 'Stundenplan',
        map: 'Karte',
        food: 'Essen',
        campusMap: 'Campus Karte',
        settings: 'Einstellungen',
        preferences: 'Präferenzen',
        flags: 'Kennzeichnungen',
        flagsSearch: 'Suche Kennzeichnungen',
        allergensSearch: 'Suche Allergene',
        allergens: 'Allergene',
        details: 'Details',
        theme: 'Design',
        profile: 'Profil',
        about: 'Über',
        advancedSearch: 'Erweiterte Suche',
        calendar: 'Kalender',
        examDetails: 'Prüfungsdetails',
        lecturers: {
            title: 'Dozenten',
            search: 'Suche alle Dozenten',
        },
        lecturer: 'Dozenten-Details',
        mobility: 'Mobilität',
        grades: 'Noten',
        news: 'THI Neuigkeiten',
    },
    cards: {
        titles: {
            timetable: 'Stundenplan',
            mobility: 'Mobilität',
            calendar: 'Kalender',
            rooms: 'Räume',
            lecturers: 'Dozenten',
            news: 'THI Neuigkeiten',
            library: 'Bibliothek',
            events: 'Veranstaltungen',
            reimanns: 'Reimanns',
            canisius: 'Canisius Konvikt',
            mensa: 'Mensa',
            food: 'Essen',
        },
        events: {
            by: 'von {{name}}',
        },
        calendar: {
            exam: 'Prüfung {{name}}',
            ends: 'endet ',
        },
    },
}
