# bunfig.toml

[test]
preload = ["./src/utils/tests/setup.ts"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
	"src/__generated__/**",
	"src/data/licenses.json",
	"src/app/**",
	"src/components/**",
	"src/assets/**",
	"src/utils/tests/**",
	"ios/**",
	"android/**"
]
