services:
    app:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
            EXPO_PUBLIC_THI_API_KEY: ${EXPO_PUBLIC_THI_API_KEY}
            EXPO_PUBLIC_NEULAND_GRAPHQL_ENDPOINT: ${EXPO_PUBLIC_NEULAND_GRAPHQL_ENDPOINT}
            EXPO_PUBLIC_APTABASE_KEY: ${EXPO_PUBLIC_APTABASE_KEY}
        volumes:
            - .:/usr/src/app
        restart: unless-stopped
