sonar.organization=neuland-ingolstadt
sonar.projectKey=neuland-ingolstadt_neuland.app-native
sonar.projectName=neuland.app-native

sonar.sources=src
sonar.tests=src/utils/tests
sonar.test.inclusions=**/*.test.ts

sonar.exclusions=**/__generated__/**,src/assets/**,src/data/licenses.json,src/data/package-licenses.json,src/uniwind-types.d.ts

sonar.coverage.exclusions=**/__generated__/**,src/assets/**,src/app/**,src/components/**,src/hooks/**,src/data/licenses.json,src/utils/tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
