name: Setup EAS CLI
description: Install Expo Application Services CLI with repository token
inputs:
  token:
    description: Expo access token
    required: true
runs:
  using: composite
  steps:
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # v9.0.0
      with:
        eas-version: latest
        token: ${{ inputs.token }}
