blank_issues_enabled: true
contact_links:
  - name: Feedback, feature requests & questions
    url: https://neuland.app/docs/app/feedback
    about: Please use this page to send feedback, request features, or ask questions.