name: Feature request
description: Submit your idea for a new feature or enhancement.
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              # Feature request
    - type: textarea
      id: description
      attributes:
          label: Feature description
          description: Describe the feature you'd like to see implemented.
      validations:
          required: true
    - type: textarea
      id: why-needed
      attributes:
          label: Why it is needed?
          description: Please tell us a bit more of why you want this feature to be added, what's its origin.
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.
      validations:
          required: false
