overwrite: true
schema: 'https://api.neuland.app/graphql'
documents: 'src/api/**/*.ts'
generates:
    'src/__generated__/gql/':
        preset: 'client'
        presetConfig:
            fragmentMasking:
                unmaskFunctionName: 'getFragmentData'
        config:
            documentMode: 'string'
    'src/__generated__/schema.graphql':
        plugins: ['schema-ast']
        config:
            includeDirectives: true
config:
    scalars:
        DateTime: 'Date'
        URL: 'string'
        LocalEndTime: 'string'
        EmailAddress: 'string'
