apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: neuland-next-web
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/neuland.app-native/webapp
  interval: 5m
