apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: neuland-next-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: neuland-next-web
  policy:
    semver:
      range: '>=0.13.0'
  filterTags:
    pattern: '^([0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$1'