name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    name: Assign PR author
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR opener
        if: github.event.pull_request.user.type != 'Bot'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.event.pull_request.user.login }}" --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
