name: "Build Android (Beta)"

on:
  workflow_dispatch:
    inputs:
      internal:
        description: "Submit as internal build"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup
        with:
          ignore-scripts: 'true'

      - uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - uses: ./.github/actions/android-prepare

      - name: Build with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_GIT_COMMIT_HASH: ${{ github.sha }}
        run: eas build --platform android --profile production --non-interactive --local --output neuland-next.aab

      - name: Determine submission profile
        run: |
          if [[ "${{ github.event.inputs.internal }}" == "true" ]]; then
            echo "SUBMIT_PROFILE=internal" >> $GITHUB_ENV
          else
            echo "SUBMIT_PROFILE=preview" >> $GITHUB_ENV
          fi

      - name: Submit to Google Play
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit --platform android --profile ${{ env.SUBMIT_PROFILE }} --non-interactive --path neuland-next.aab
