name: Build and publish staging Docker image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/webapp

jobs:
  changes:
    name: Detect Docker-related changes
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.detect.outputs.docker }}
      workflows: ${{ steps.detect.outputs.workflows }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Detect changes
        uses: ./.github/actions/detect-changes
        id: detect

  build-and-push-image:
    name: Build and publish staging image
    needs: changes
    if: |
      needs.changes.outputs.docker == 'true' ||
      needs.changes.outputs.workflows == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=staging-${{ github.run_number }}
            type=ref,event=branch,pattern=^main$
            type=raw,value=staging-latest
          flavor: |
            latest=false

      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: config/Dockerfile
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            type=staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            EXPO_PUBLIC_THI_API_KEY=${{ secrets.EXPO_PUBLIC_THI_API_KEY }}
            EXPO_PUBLIC_NEULAND_AUTHENTIK_CLIENT_ID=${{ secrets.EXPO_PUBLIC_NEULAND_AUTHENTIK_CLIENT_ID }}
            EXPO_PUBLIC_NEULAND_GRAPHQL_ENDPOINT=${{ vars.GRAPHQL_ENDPOINT_DEV }}
            EXPO_PUBLIC_APTABASE_KEY=${{ secrets.EXPO_PUBLIC_APTABASE_KEY }}
            EXPO_PUBLIC_FLIPT_URL=https://flipt.neuland.ing
            EXPO_PUBLIC_FLIPT_NAMESPACE=neuland-app
            EXPO_PUBLIC_GIT_COMMIT_HASH=${{ github.sha }}
