name: Native fingerprint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  EXPO_PUBLIC_THI_API_KEY: ${{ secrets.EXPO_PUBLIC_THI_API_KEY }}
  EXPO_PUBLIC_NEULAND_AUTHENTIK_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_NEULAND_AUTHENTIK_CLIENT_ID }}
  EXPO_PUBLIC_NEULAND_GRAPHQL_ENDPOINT: ${{ vars.GRAPHQL_ENDPOINT_PROD }}
  EXPO_PUBLIC_APTABASE_KEY: ${{ secrets.EXPO_PUBLIC_APTABASE_KEY }}
  EXPO_PUBLIC_FLIPT_URL: https://flipt.neuland.ing
  EXPO_PUBLIC_FLIPT_NAMESPACE: neuland-app
  EXPO_PUBLIC_GIT_COMMIT_HASH: ${{ github.sha }}

jobs:
  fingerprint:
    name: Check native fingerprint
    runs-on: ubuntu-latest
    outputs:
      fingerprint-diff: ${{ steps.fingerprint.outputs.fingerprint-diff }}
    concurrency: fingerprint-${{ github.event_name != 'pull_request' && 'main' || github.run_id }}
    permissions:
      pull-requests: write
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - uses: ./.github/actions/setup

      - name: Check fingerprint
        id: fingerprint
        uses: expo/expo-github-action/fingerprint@eab7a230208c952974db8c3245cfd78402c7b385 # v9

      - name: Label compatible PR
        if: ${{ github.event_name == 'pull_request' && steps.fingerprint.outputs.fingerprint-diff == '[]' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const labels = {
              add: ['fp:compatible'],
              remove: ['fp:changed'],
            }

            for (const name of labels.remove) {
              try {
                await github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name,
                })
              } catch (error) {
                if (error.status !== 404) {
                  throw error
                }
              }
            }

            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels.add,
            })

      - name: Label changed PR
        if: ${{ github.event_name == 'pull_request' && steps.fingerprint.outputs.fingerprint-diff != '[]' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const labels = {
              add: ['fp:changed'],
              remove: ['fp:compatible'],
            }

            for (const name of labels.remove) {
              try {
                await github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name,
                })
              } catch (error) {
                if (error.status !== 404) {
                  throw error
                }
              }
            }

            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels.add,
            })

  build-android-dev-client:
    name: Build Android dev client
    needs: fingerprint
    if: |
      github.event_name == 'push' &&
      needs.fingerprint.outputs.fingerprint-diff != '[]'
    runs-on: ubuntu-latest
    concurrency:
      group: android-dev-client-main
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Bundle licenses
        run: bun run licences:bundle

      - name: Build dev client on EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile development --non-interactive

  build-ios-dev-client:
    name: Build iOS dev client
    needs: fingerprint
    if: |
      github.event_name == 'push' &&
      needs.fingerprint.outputs.fingerprint-diff != '[]'
    runs-on: ubuntu-latest
    concurrency:
      group: ios-dev-client-main
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/setup-eas
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Bundle licenses
        run: bun run licences:bundle

      - name: Build dev client on EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --profile development --non-interactive
