name: CI ESLint
on:
    push:
        branches: [develop, main]
    pull_request:
        branches: [develop, main]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/checkout@v4
            - name: Install modules
              run: bun install --frozen-lockfile
            - name: Run ESLint
              run: bunx eslint . --ext .js,.jsx,.ts,.tsx
