name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:
    types: [checks_requested]

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request_target'
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          subjectPattern: ^[^A-Z].*[^.]$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'merge_group'
        run: echo "PR title was validated before entering the merge queue."
