name: Expo Go Update
on:
  push:
    branches:
      - main
      - develop
    
jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: 'rogue-thi-app/yarn.lock'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install
        working-directory: rogue-thi-app/

      - name: Publish update
        env:
          EXPO_PUBLIC_THI_API_KEY: ${{ secrets.THI_API_KEY }}
        run: eas update --auto
        working-directory: rogue-thi-app/
